class AppStrings {
  // English
  static const Map<String, String> enUS = {
    'appName': 'Moon Calendar',
    'calendar': 'Calendar',
    'details': 'Details',
    'moonDetails': 'Moon Details',
    'phaseName': 'Phase Name',
    'illumination': 'Illumination',
    'daysUntilFullMoon': 'Days Until Full Moon',
    'lunarCycle': 'Lunar Cycle',
    'daysSinceNewMoon': 'Days Since New Moon',
    'lunarMonthLength': 'Lunar Month Length',
    'julianDayNumber': 'Julian Day Number',
    'phaseTimeline': 'Phase Timeline',
    'moonPhaseInformation': 'Moon Phase Information',
    'illuminationVisualization': 'Illumination Visualization',
    'lunarCycleInformation': 'Lunar Cycle Information',
    'newMoon': 'New Moon',
    'waxingCrescent': 'Waxing Crescent',
    'firstQuarter': 'First Quarter',
    'waxingGibbous': 'Waxing Gibbous',
    'fullMoon': 'Full Moon',
    'waningGibbous': 'Waning Gibbous',
    'lastQuarter': 'Last Quarter',
    'waningCrescent': 'Waning Crescent',
    'selectedDate': 'Selected Date',
    'currentMoonPhase': 'Current Moon Phase',
    'festivals': 'Festivals',
    'noFestival': 'No festival this day',
    'howAreYouFeeling': 'How Are You Feeling Today?',
    'moonCyclesAffect': 'Studies show moon cycles affect mood & emotions',
    'trackMoodMessage': 'Have you felt excited for no reason? Argued with family or friends? Let\'s track it!',
    'moodRecorded': 'Mood recorded! Track patterns to understand your lunar connection.',
    'excited': 'Excited',
    'calm': 'Calm',
    'sad': 'Sad',
    'angry': 'Angry',
    'anxious': 'Anxious',
    'neutral': 'Neutral',
    'trackYourMood': 'Track Your Mood',
    'yourEnergyLevel': 'What\'s Your Energy Level?',
    'workProductivityStatus': 'Work & Productivity Status',
    'energetic': 'Energetic',
    'normal': 'Normal',
    'tired': 'Tired',
    'lethargic': 'Lethargic',
    'excited_finish': 'Excited to Finish Work',
    'focused': 'Focused & Productive',
    'procrastinating': 'Procrastinating',
    'delayed': 'Delaying Work',
    'not_working': 'Not Working',
    'step': 'Step',
    'back': 'Back',
    'next': 'Next',
    'save': 'Save',
    'pleaseSelectAll': 'Please select all options',
    'errorLoadingMoonData': 'Error loading moon data',
    'moodSavedSuccess': 'Mood saved successfully!',
    'moodTrackingTitle': '✨ Track Your Emotional Journey',
    'moodTrackingDescription': 'Did you argue with someone today? Feel happy for no reason? Excited to finish work? Track it all! Understand how the moon\'s cycles influence your emotions, energy levels, and productivity patterns.',
    'nextMoonPhase': 'Next Moon Phase',
    'daysUntil': 'days until',
  };

  // Japanese (日本語)
  static const Map<String, String> jaJP = {
    'appName': 'ムーンカレンダー',
    'calendar': 'カレンダー',
    'details': '詳細',
    'moonDetails': '月の詳細',
    'phaseName': '月の満ち欠け',
    'illumination': '照度',
    'daysUntilFullMoon': '満月まで日数',
    'lunarCycle': '太陰暦周期',
    'daysSinceNewMoon': '新月からの日数',
    'lunarMonthLength': '太陰月の長さ',
    'julianDayNumber': 'ユリウス日番号',
    'phaseTimeline': '月相タイムライン',
    'moonPhaseInformation': '月相情報',
    'illuminationVisualization': '照度の可視化',
    'lunarCycleInformation': '太陰暦周期情報',
    'newMoon': '新月',
    'waxingCrescent': '三日月',
    'firstQuarter': '上弦の月',
    'waxingGibbous': '盛月',
    'fullMoon': '満月',
    'waningGibbous': '寝待月',
    'lastQuarter': '下弦の月',
    'waningCrescent': '有明月',
    'selectedDate': '選択した日付',
    'currentMoonPhase': '現在の月相',
    'festivals': 'お祭り',
    'noFestival': 'この日はお祭りはありません',
    'howAreYouFeeling': '今日はどんな気分ですか？',
    'moonCyclesAffect': '月のサイクルが気分や感情に影響することが知られています',
    'trackMoodMessage': '特に理由もなく興奮しましたか？家族や友人と喧嘩しましたか？記録しましょう！',
    'moodRecorded': '気分が記録されました！パターンを追跡して月との関係を理解しましょう。',
    'excited': '興奮',
    'calm': '落ち着き',
    'sad': '悲しい',
    'angry': '怒り',
    'anxious': '不安',
    'neutral': 'ニュートラル',
    'trackYourMood': 'あなたの気分を記録する',
    'yourEnergyLevel': 'あなたのエネルギーレベルは？',
    'workProductivityStatus': '仕事と生産性の状態',
    'energetic': 'エネルギッシュ',
    'normal': '普通',
    'tired': '疲れた',
    'lethargic': '無気力',
    'excited_finish': '仕事を終わらせたい',
    'focused': '集中力がある',
    'procrastinating': '先延ばししている',
    'delayed': '仕事が遅れている',
    'not_working': '仕事をしていない',
    'step': 'ステップ',
    'back': '戻る',
    'next': '次へ',
    'save': '保存',
    'pleaseSelectAll': 'すべてのオプションを選択してください',
    'errorLoadingMoonData': 'ムーンデータの読み込みエラー',
    'moodSavedSuccess': '気分が正常に保存されました！',
    'moodTrackingTitle': '✨ あなたの感情を記録しましょう',
    'moodTrackingDescription': '今日、䮤気で鎧めましたか？年んで法夸い年月を感じましたか？仕事を終わらせたい気持ちを感じましたか？すべて記録しましょう！月のサイクルがあなたの感情、エネルギー、生産性に如何影響を与えるかを理解しましょう。',
    'nextMoonPhase': '次の月の満ち欠け',
    'daysUntil': '日後に',
  };

  // Korean (한국어)
  static const Map<String, String> koKR = {
    'appName': '달 달력',
    'calendar': '달력',
    'details': '상세 정보',
    'moonDetails': '달 상세 정보',
    'phaseName': '달의 위상',
    'illumination': '조명도',
    'daysUntilFullMoon': '보름달까지 날수',
    'lunarCycle': '음력 사이클',
    'daysSinceNewMoon': '새로운 달부터의 날수',
    'lunarMonthLength': '음력월의 길이',
    'julianDayNumber': '줄리안 일수',
    'phaseTimeline': '달의 위상 타임라인',
    'moonPhaseInformation': '달의 위상 정보',
    'illuminationVisualization': '조명도 시각화',
    'lunarCycleInformation': '음력 사이클 정보',
    'newMoon': '새로운 달',
    'waxingCrescent': '초승달',
    'firstQuarter': '상현달',
    'waxingGibbous': '머금은 달',
    'fullMoon': '보름달',
    'waningGibbous': '깎아내리는 달',
    'lastQuarter': '하현달',
    'waningCrescent': '그믐달',
    'selectedDate': '선택한 날짜',
    'currentMoonPhase': '현재 달의 위상',
    'festivals': '축제',
    'noFestival': '이 날 축제가 없습니다',
    'howAreYouFeeling': '오늘은 어떤 기분이세요?',
    'moonCyclesAffect': '달의 주기가 기분과 감정에 영향을 미친다는 연구 결과가 있습니다',
    'trackMoodMessage': '특별한 이유 없이 흥분했나요? 가족이나 친구와 싸웠나요? 기록해보세요!',
    'moodRecorded': '기분이 기록되었습니다! 패턴을 추적하여 달과의 관계를 이해해보세요.',
    'excited': '흥분',
    'calm': '차분',
    'sad': '슬픔',
    'angry': '분노',
    'anxious': '불안',
    'neutral': '중립',
    'trackYourMood': '기분 기록하기',
    'yourEnergyLevel': '에너지 수준은 어떻게 되나요?',
    'workProductivityStatus': '일 및 생산성 상태',
    'energetic': '활기찬',
    'normal': '보통',
    'tired': '피곤함',
    'lethargic': '무기력함',
    'excited_finish': '일을 끝내고 싶음',
    'focused': '집중력 있음',
    'procrastinating': '미루고 있음',
    'delayed': '일이 지연됨',
    'not_working': '일을 하지 않음',
    'step': '단계',
    'back': '돌아가기',
    'next': '다음',
    'save': '저장',
    'pleaseSelectAll': '모든 옵션을 선택하세요',
    'errorLoadingMoonData': '달 데이터 로드 오류',
    'moodSavedSuccess': '기분이 성공적으로 저장되었습니다!',
    'moodTrackingTitle': '✨ 당다른 감정을 기록하세요',
    'moodTrackingDescription': '오늘 놜 사람과 싸웠나요? 이유 없이 행복했나요? 일을 끝내고 싶은 기분이 들나요? 모두 기록할 수 있습니다! 달의 쏼기가 당신의 감정, 에너지, 생산성에 어떻게 영향을 미치는지 더 재미있게 알아보세요.',
    'nextMoonPhase': '다음 달의 위상',
    'daysUntil': '일 후',
  };

  // Simplified Chinese (简体中文)
  static const Map<String, String> zhCN = {
    'appName': '月亮日历',
    'calendar': '日历',
    'details': '详情',
    'moonDetails': '月亮详情',
    'phaseName': '月相',
    'illumination': '亮度',
    'daysUntilFullMoon': '距离满月天数',
    'lunarCycle': '农历周期',
    'daysSinceNewMoon': '自新月以来的天数',
    'lunarMonthLength': '农历月长度',
    'julianDayNumber': '儒略日号',
    'phaseTimeline': '月相时间线',
    'moonPhaseInformation': '月相信息',
    'illuminationVisualization': '亮度可视化',
    'lunarCycleInformation': '农历周期信息',
    'newMoon': '新月',
    'waxingCrescent': '蛾眉月',
    'firstQuarter': '上弦月',
    'waxingGibbous': '盈凸月',
    'fullMoon': '满月',
    'waningGibbous': '亏凸月',
    'lastQuarter': '下弦月',
    'waningCrescent': '残月',
    'selectedDate': '选定日期',
    'currentMoonPhase': '当前月相',
    'festivals': '节日',
    'noFestival': '这一天没有节日',
    'howAreYouFeeling': '你今天感觉如何？',
    'moonCyclesAffect': '研究表明月亮周期会影响情绪和感情',
    'trackMoodMessage': '你是否无缘无故感到兴奋？与家人或朋友争执过？让我们追踪它！',
    'moodRecorded': '心情已记录！追踪模式以了解您与月亮的联系。',
    'excited': '兴奋',
    'calm': '平静',
    'sad': '悲伤',
    'angry': '愤怒',
    'anxious': '焦虑',
    'neutral': '中立',
    'trackYourMood': '记录你的心情',
    'yourEnergyLevel': '你的能量水平如何？',
    'workProductivityStatus': '工作和生产力状态',
    'energetic': '充满活力',
    'normal': '正常',
    'tired': '疲劳',
    'lethargic': '精神不振',
    'excited_finish': '想完成工作',
    'focused': '专注',
    'procrastinating': '拖延中',
    'delayed': '工作延迟',
    'not_working': '未工作',
    'step': '步骤',
    'back': '返回',
    'next': '下一个',
    'save': '保存',
    'pleaseSelectAll': '请选择所有选项',
    'errorLoadingMoonData': '加载月球数据错误',
    'moodSavedSuccess': '心情保存成功！',
    'moodTrackingTitle': '✨ 记录你的情感旅程',
    'moodTrackingDescription': '今天你是否与某人争执过？是否无理由地感到了幸正？是否激激想完成工作？记录一切！了解月亮的周期如何影响你的情感、能量水平和工作效率。',
    'nextMoonPhase': '下一个月相',
    'daysUntil': '天后',
  };

  // Hindi (हिंदी)
  static const Map<String, String> hiIN = {
    'appName': 'चंद्र कैलेंडर',
    'calendar': 'कैलेंडर',
    'details': 'विवरण',
    'moonDetails': 'चंद्र विवरण',
    'phaseName': 'चाँद की स्थिति',
    'illumination': 'रोशनी',
    'daysUntilFullMoon': 'पूर्णिमा तक दिन',
    'lunarCycle': 'चंद्र चक्र',
    'daysSinceNewMoon': 'नए चाँद के बाद दिन',
    'lunarMonthLength': 'चंद्र मास की लंबाई',
    'julianDayNumber': 'जूलियन दिन संख्या',
    'phaseTimeline': 'चंद्र चरण समयरेखा',
    'moonPhaseInformation': 'चंद्र चरण जानकारी',
    'illuminationVisualization': 'रोशनी दृश्य',
    'lunarCycleInformation': 'चंद्र चक्र जानकारी',
    'newMoon': 'अमावस्या',
    'waxingCrescent': 'शुक्ल पक्ष',
    'firstQuarter': 'प्रथम चतुर्थांश',
    'waxingGibbous': 'बढ़ता पूर्ण चंद्र',
    'fullMoon': 'पूर्णिमा',
    'waningGibbous': 'कृष्ण पक्ष',
    'lastQuarter': 'अंतिम चतुर्थांश',
    'waningCrescent': 'घटता चंद्र',
    'selectedDate': 'चयनित तारीख',
    'currentMoonPhase': 'वर्तमान चंद्र स्थिति',
    'festivals': 'त्योहार',
    'noFestival': 'इस दिन कोई त्योहार नहीं',
    'howAreYouFeeling': 'आज आप कैसा महसूस कर रहे हैं?',
    'moonCyclesAffect': 'अध्ययन से पता चलता है कि चंद्र चक्र मनोदशा और भावनाओं को प्रभावित करते हैं',
    'trackMoodMessage': 'क्या आप बिना किसी कारण के उत्साहित महसूस कर रहे हैं? परिवार या दोस्तों से झगड़ा किया? आइए इसे ट्रैक करें!',
    'moodRecorded': 'मनोदशा रिकॉर्ड की गई! पैटर्न को ट्रैक करें और चंद्र संबंध को समझें।',
    'excited': 'उत्साही',
    'calm': 'शांत',
    'sad': 'उदास',
    'angry': 'क्रोधित',
    'anxious': 'चिंतित',
    'neutral': 'तटस्थ',
    'trackYourMood': 'अपना मूड ट्रैक करें',
    'yourEnergyLevel': 'आपकी ऊर्जा का स्तर क्या है?',
    'workProductivityStatus': 'काम और उत्पादकता स्थिति',
    'energetic': 'ऊर्जावान',
    'normal': 'सामान्य',
    'tired': 'थका हुआ',
    'lethargic': 'सुस्त',
    'excited_finish': 'काम पूरा करने के लिए उत्सुक',
    'focused': 'केंद्रित',
    'procrastinating': 'टाल रहे हैं',
    'delayed': 'काम विलंबित',
    'not_working': 'काम नहीं कर रहे',
    'step': 'चरण',
    'back': 'वापस',
    'next': 'अगला',
    'save': 'सहेजें',
    'pleaseSelectAll': 'कृपया सभी विकल्प चुनें',
    'errorLoadingMoonData': 'चंद्र डेटा लोड करने में त्रुटि',
    'moodSavedSuccess': 'मूड सफलतापूर्वक सहेजा गया!',
    'moodTrackingTitle': '✨ अपनी धावक सँधर्ष की यातिध रिकॉर्ड करें',
    'moodTrackingDescription': 'क्या आप आज किसी से केण लिए? बिला किसी कारण खुश महसूस करे? काम तेज संरह करवाग हों? समस्त बातें गुश करें! समृझें कि चंध्र की गतों कई तरह से आपके महसूस, ऊर्जा और उत्सता कैस प्रभावित करती हैं।',
    'nextMoonPhase': 'अगला चंद्र चरण',
    'daysUntil': 'दिन बाद',
  };

  static Map<String, String> getStrings(String languageCode) {
    switch (languageCode) {
      case 'ja':
        return jaJP;
      case 'ko':
        return koKR;
      case 'zh':
        return zhCN;
      case 'hi':
        return hiIN;
      default:
        return enUS;
    }
  }
}
